### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by saadidrees711**
@shahbaz-mehar please review the pull request.

### CODE REVIEW

**Review by shahbaz-mehar — COMMENTED** [review]
Changes have been reviewed.

**Comment by emicha** [comment]
Please follow the same heading structure as we did with the other plugins:
Intro to altapay and plugin
- Prerequisites
- Installation
- Configuration
- Supported Verisons
etc

**Comment by emicha** [comment]
The images are showing the Adyen logo, is there a way to hide this?

Are these screenshots up to date?

**Comment by saadidrees711** [comment]
@emicha suggested changes have been implemented. Please review.

**Review by emicha — APPROVED** [review]

**Pull request merged**
